name: my

on:
#    schedule:
#      - cron: '0 0 * * *'
    push:
    workflow_dispatch:

jobs:
  Run-Analysis:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'vskrishnan-run')
    timeout-minutes: 5760 #4 days 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Set execute permission for the script
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh
          chmod +x $GITHUB_WORKSPACE/scripts/domainRotator.sh

      - name: Run DomainRotator
        run : bash $GITHUB_WORKSPACE/scripts/domainRotator.sh

      - name: Notify Start Status
        run: |
          bash $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh start

      - name: Send Domain List
        run: |
          bash $GITHUB_WORKSPACE/scripts/notify/sendDomainList.sh   
      
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.6

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev # Required for Naabu

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          go install github.com/projectdiscovery/notify/cmd/notify@latest
        shell: bash
      
      - name: Current Directory path
        run: |
          pwd
        shell: bash

      - name: Running SubFinder for passive DNS enumeration
        run: |
          subfinder -dL input/domains.txt -config config/subfinder-config.yaml -o output/passive_subdomains.txt
        shell: bash

      - name: Notify Passive Domains Count  
        run: |
          bash $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh "Passive Subdomains : $(cat $GITHUB_WORKSPACE/output/passive_subdomains.txt |wc -l)"

      - name: Running dnsx for valid DNS filtering 
        run: |
          dnsx -l output/passive_subdomains.txt -t 50 | tee output/active_subdomains.txt
        shell: bash
        
      - name: Notify Active Sub Domains Count  
        run: |
          bash $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh "Active Subdomains : $(cat $GITHUB_WORKSPACE/output/active_subdomains.txt |wc -l)"  
      
      - name: List output directry
        run: |
          ls -lt output/
        shell: bash  
      - name: Log naabu version
        run: |
          naabu --version
        shell: bash

      - name: Running naabu to check top 100 ports
        run: |
          naabu -l /home/runner/work/pd-actions/pd-actions/output/active_subdomains.txt -rate 10000 | tee /home/runner/work/pd-actions/pd-actions/output/active_ports.txt
        shell: bash

      - name: Notify Active Ports Count  
        run: |
          bash $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh "Active Ports : $(cat $GITHUB_WORKSPACE/output/active_ports.txt |wc -l)"      

      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt | tee output/active_urls.txt
        shell: bash

      - name: Notify Active urls Count  
        run: |
          bash $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh "Active Urls : $(cat $GITHUB_WORKSPACE/output/active_urls.txt |wc -l)"      
    
      - name: Downloading Nuclei Templates
        run: |
          nuclei -update-templates
        shell: bash

      - name: List Nuclei Templates
        run: |
          ls -lt /home/runner/nuclei-templates
        shell: bash

      - name: Running Nuclei for vulnerability assessment
        run: |
          nuclei -t cves/ -l output/active_urls.txt -bs 100 -c 50 -rl 300 -nc | tee output/nuclei_output.txt
        shell: bash

      - name: Notify Status End
        run: |
          bash $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh end

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

          # git add output/passive_subdomains.txt
          # git add output/active_subdomains.txt
          # git add output/active_ports.txt
          # git add output/active_urls.txt
      - name: Create local changes
        run: |
          git pull
          git add output/nuclei_output.txt
          git add input/

      - name: Commit results to Github
        run: |
          git config --local user.email "vskrishnan27@gmail.com"
          git config --global user.name "vskrishnan27"
          git commit -m "vskrishnan-run" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  run-if-not-keyword:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'vskrishnan-run') }}
    timeout-minutes: 5760 #4 days 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Run Different Script
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh
          combined_message="message doesn't contain keyword - ${{ github.event.head_commit.message }}"
          bash $GITHUB_WORKSPACE/scripts/notify/discordNotify.sh "$combined_message"
        env:
            GITHUB_WORKSPACE: ${{ github.workspace }}    
